apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediwiki-pv-2
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/pv-mongo-3
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem