apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediwiki-pvc-1
  namespace: challengetwo
  labels:
    microservice: cnfrs
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mediawiki-pv-1

